config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#homepage'

  get 'homepage', to: 'home#homepage'
  get 'dashboard', to: 'home#dashboard'

  resources :houses, only: [:index, :show, :new, :create, :update] do
    resources :deals, only: [:new, :create, :edit, :update]
  end

  resources :deals, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  belongs_to :house
  has_many :units, through: :house

  validates :interest_rate, :down_payment_percentage, :purchase_price,
  :loan_term_years, :rehab_cost, :holding_cost,
  :utilities, :lawn_care, :insurance,
  :vacancy, :maintenance, :capital_expenditure,
  :property_management, :closing_costs, presence: true

  scope :for_user, ->(user_id) { where(user_id: user_id).joins(:house) }

  after_initialize if:  :new_record? do
    self.down_payment_percentage ||= 3.5
  end

  def total_cash_needed
    calculate_total_cash_needed(purchase_price, purchase_price)
  end

  def total_income
    income = 0
    units.each do |unit|
      income = income + unit.monthly_rent
    end
    income
  end

  def total_expenses
    vacancy_amount = vacancy * total_income / 100.0
    maintenance_amount = maintenance * total_income / 100.0
    capex_amount = capital_expenditure * total_income / 100.0
    management_amount = property_management * total_income / 100.0
    vacancy_amount + maintenance_amount + capex_amount + management_amount +
    utilities + lawn_care + insurance + house.annual_property_taxes/12.0
  end

  def monthly_payment
    calculate_monthly_payment purchase_price, purchase_price
  end

  def net_operating_income
    total_income - total_expenses
  end

  def cash_flow
    calculate_cash_flow monthly_payment
  end

  def cash_on_cash_return
    calculate_cash_on_cash_return cash_flow, total_cash_needed
  end

  def max_purchase_price(accuracy, max_iterations)
    max_purchase_price = house.list_price

    target_return_lower_bound = 7.5
    target_return_upper_bound = 8.5

    incremented_up = false
    incremented_down = false

    iterations = 0

    loop do
      iterations += 1

      monthly_payment = calculate_monthly_payment(purchase_price, max_purchase_price)
      total_cash_needed = calculate_total_cash_needed(purchase_price, max_purchase_price)
      cash_flow = calculate_cash_flow(monthly_payment)
      cash_on_cash_return = calculate_cash_on_cash_return(cash_flow, total_cash_needed)

      if cash_on_cash_return >= target_return_lower_bound && cash_on_cash_return <= target_return_upper_bound
        break
      elsif cash_on_cash_return < target_return_lower_bound
        max_purchase_price -= accuracy
        incremented_down = true
      else
        max_purchase_price += accuracy
        incremented_up = true
      end

      if incremented_down && incremented_up
        break
      end

      if iterations >= max_iterations
        max_purchase_price = " / Max Purchase Price Too Far From Listing Price: Bad Deal"
        break
      end
    end

    max_purchase_price
  end
  #
  # def max_purchase_price a, b
  #   money_down = down_payment_percentage * purchase_price / 100.0
  #   monthly_interest_rate = interest_rate / 12.0 / 100.0
  #   total_payments = loan_term_years * 12
  #   price = (100 * (money_down - 150 * money_down * monthly_interest_rate) * ((-monthly_interest_rate + 1)**total_payments) -  money_down * ((-monthly_interest_rate + 1)**total_payments) + rehab_cost + holding_cost - (rehab_cost * (-monthly_interest_rate + 1)**total_payments) - (holding_cost * (-monthly_interest_rate + 1)**total_payments))/
  #   ((-closing_costs) + (closing_costs * (-monthly_interest_rate + 1)**total_payments) - ((15000 * monthly_interest_rate) * (-monthly_interest_rate + 1)**total_payments))
  #   price
  # end


private

  def calculate_monthly_payment user_purchase_price, new_purchase_price
    money_down = down_payment_percentage * user_purchase_price / 100.0
    loan_amount = new_purchase_price - money_down
    monthly_interest_rate = interest_rate / 12.0 / 100.0
    total_payments = loan_term_years * 12
    monthly_payment = (loan_amount * monthly_interest_rate * (1 + monthly_interest_rate)**total_payments) / ((1 + monthly_interest_rate)**total_payments - 1)
    monthly_payment = (monthly_payment * 100).ceil / 100.0
    monthly_payment
  end

  def calculate_total_cash_needed user_purchase_price, new_purchase_price
    down_payment = down_payment_percentage * user_purchase_price / 100.0
    closing_expense = closing_costs * new_purchase_price / 100.0
    down_payment + closing_expense + rehab_cost + holding_cost
  end

  def calculate_cash_flow monthly_payment
    net_operating_income - monthly_payment
  end

  def calculate_cash_on_cash_return cash_flow, total_cash_needed
    (cash_flow * 12 / total_cash_needed * 100).round(2)
  end

end

app/models/house.rb
class House < ApplicationRecord
  has_many :units, dependent: :destroy
  has_many :deals, dependent: :destroy
  has_many :users, through: :deals

  validates :address, :list_price, :annual_property_taxes, :year_built, presence: true

  accepts_nested_attributes_for :units, allow_destroy: true, reject_if: :all_blank
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :house

  validates :bedrooms, :bathrooms, :monthly_rent, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :deals, dependent: :destroy
  has_many :houses, through: :deals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!

  def index
    @deals = Deal.for_user(current_user.id)
  end

  def new
    @house = House.find(params[:house_id])
    @deal = @house.deals.new
  end

  def create
    @house = House.find(params[:house_id])
    @deal = @house.deals.new(deal_params)
    @deal.user = current_user

    if @deal.save
      redirect_to house_path(@house), notice: "Deal was successfully created."
    else
      render :new
    end
  end

  def edit
    @house = House.find(params[:house_id])
    @deal = @house.deals.find(params[:id])
  end

  def update
    @house = House.find(params[:house_id])
    @deal = @house.deals.find(params[:id])

    if @deal.update(deal_params)
      redirect_to house_path(@house), notice: "Deal was successfully updated."
    else
      render :edit
    end
  end

  private

  def deal_params
    params.require(:deal).permit(
      :interest_rate, :down_payment_percentage, :purchase_price,
      :loan_term_years, :rehab_cost, :holding_cost,
      :utilities, :lawn_care, :insurance,
      :vacancy, :maintenance, :capital_expenditure,
      :property_management, :closing_costs
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[homepage]

  def homepage; end
  def dashboard; end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :update]

  def index
    @houses = House.all
    @house = House.new
    4.times { @house.units.build }
  end

  def show; end

  def create
    @houses = House.all
    @house = House.new(house_params)
    if @house.save
      redirect_to @house, notice: "House was successfully created."
    else
      render :index
    end
  end

  def update
    if @house.update(house_params)
      redirect_to house_path(@house), notice: "House was successfully updated."
    else
      render :show
    end
  end

  def house_params
    params.require(:house).permit(
      :address, :list_price, :annual_property_taxes, :year_built,
      units_attributes: [:id, :bedrooms, :bathrooms, :monthly_rent, :_destroy]
    )
  end

private

  def set_house
    @house = House.find(params[:id])
    @deal = @house.deals.find_or_initialize_by(user: current_user)
  end
end

app/controllers/unit_controller.rb
class UnitController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deals/_form.html.erb
  <%= form_with(model: [house, deal], local: true) do |f| %>

<div class="field">
  <%= f.label :interest_rate, "Interest Rate (%)" %>
  <%= f.number_field :interest_rate, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :down_payment_percentage, "Down Payment (%)" %>
  <%= f.number_field :down_payment_percentage, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :purchase_price, "Purchase Price" %>
  <%= f.number_field :purchase_price, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :loan_term_years, "Loan Term (Years)" %>
  <%= f.number_field :loan_term_years, value: deal.loan_term_years|| 30%>
</div>

<div class="field">
  <%= f.label :rehab_cost, "Rehab Cost" %>
  <%= f.number_field :rehab_cost, value: @deal.rehab_cost || 0, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :holding_cost, "Holding Cost" %>
  <%= f.number_field :holding_cost, value: @deal.holding_cost || 0, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :utilities, "Utilities" %>
  <%= f.number_field :utilities, value: @deal.utilities, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :lawn_care, "Lawn Care" %>
  <%= f.number_field :lawn_care, value: @deal.lawn_care, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :insurance, "Insurance" %>
  <%= f.number_field :insurance, value: @deal.insurance, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :vacancy, "Vacancy (%)" %>
  <%= f.number_field :vacancy, value: @deal.vacancy || 5, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :maintenance, "Maintenance (%)" %>
  <%= f.number_field :maintenance, value: @deal.maintenance || 5, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :capital_expenditure, "Capital Expenditure (%)" %>
  <%= f.number_field :capital_expenditure, value: @deal.capital_expenditure || 5, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :property_management, "Property Management (%)" %>
  <%= f.number_field :property_management, value: @deal.property_management || 10, step: 0.01 %>
</div>

<div class="field">
  <%= f.label :closing_costs, "Closing Costs (%)" %>
  <%= f.number_field :closing_costs, value: @deal.closing_costs || 5, step: 0.01 %>
</div>

 <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/deals/index.html.erb
<div class="container my-4">
  <h1 class="mb-4">
    <%= link_to "Houses Index Page", houses_path, class: "btn btn-primary" %>
  </h1>

  <h1>Your Deals</h1>

  <% @deals.each do |deal| %>
    <div class="card mb-3">
      <div class="card-body">
        <h3 class="card-title"><%= link_to deal.house.address, house_path(deal.house) %></h3>
        <ul class="list-unstyled">
          <li><strong>List Price:</strong> $<%= deal.house.list_price %></li>
          <li><strong>Max Purchase Price:</strong> $<%= deal.max_purchase_price 10000, 15 %></li>
          <li><strong>Year Built:</strong> <%= deal.house.year_built %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/home/dashboard.html.erb
<h1> Dashboard </h1>

app/views/home/homepage.html.erb
<div class="container my-4 d-flex justify-content-center">
  <div class="text-center">
    <%= link_to "Houses Index Page", houses_path, class: "btn btn-primary btn-lg mx-2" %>
    <%= link_to "Deals Index Page", deals_path, class: "btn btn-primary btn-lg mx-2" %>
  </div>
</div>

app/views/houses/_form.html.erb
  <%= form_with(model: house, local: true, class: "mt-4") do |f| %>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :list_price %>
      <%= f.number_field :list_price, step: 0.01, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :annual_property_taxes %>
      <%= f.number_field :annual_property_taxes, step: 0.01, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :year_built %>
      <%= f.number_field :year_built, class: "form-control" %>
    </div>

    <h3 class="mt-4">Units</h3>
    <%= f.fields_for :units do |unit_form| %>
      <div class="card mb-3">
        <div class="card-body">
          <div class="form-group">
            <%= unit_form.label :bedrooms, "Number of Bedrooms" %>
            <%= unit_form.number_field :bedrooms, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= unit_form.label :bathrooms, "Number of Bathrooms" %>
            <%= unit_form.number_field :bathrooms, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= unit_form.label :monthly_rent, "Monthly Rent" %>
            <%= unit_form.number_field :monthly_rent, step: 0.01, class: "form-control" %>
          </div>

          <div class="form-check">
            <%= unit_form.check_box :_destroy, class: "form-check-input" %>
            <%= unit_form.label :_destroy, "Remove Unit", class: "form-check-label" %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>

app/views/houses/index.html.erb
<div class="container my-4">
  <h1><%= link_to "Deals Index Page", deals_path, class: "btn btn-primary mb-4" %></h1>

  <h1>All Houses</h1>

  <% @houses.each do |house| %>
    <%= render(HouseCardComponent.new(house: house)) %>
  <% end %>

  <h2 class="mt-4">Add New House</h2>

  <% if @house.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h4>
      <ul>
        <% @house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <%= render 'form', house: @house %>

</div>

app/views/houses/show.html.erb
<div class="container my-4">
  <div class="mb-4">
    <!-- Link to the Houses Index Page -->
    <%= link_to "Houses Index Page", houses_path, class: "btn btn-primary mr-2" %>

    <!-- Link to the Deals Index Page -->
    <%= link_to "Deals Index Page", deals_path, class: "btn btn-secondary" %>
  </div>

  <%= render 'form', house: @house%>

  <h3 class="mt-4">Deal</h3>

  <% if @deal.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h4><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h4>
      <ul>
        <% @deal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <% if @house.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h4><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h4>
      <ul>
        <% @house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render '/deals/form', house: @house, deal: @deal %>

  <% if @deal.persisted? %>
    <div class="mt-4">
      <h4>Deal Summary</h4>
      <ul class="list-group">
        <li class="list-group-item"><strong>Total Cash Needed:</strong> $<%= @deal.total_cash_needed %></li>
        <li class="list-group-item"><strong>Total Income:</strong> $<%= @deal.total_income %>/month</li>
        <li class="list-group-item"><strong>Total Expenses:</strong> $<%= @deal.total_expenses %>/month</li>
        <li class="list-group-item"><strong>Monthly Payment:</strong> $<%= @deal.monthly_payment %></li>
        <li class="list-group-item"><strong>Net Operating Income:</strong> $<%= @deal.net_operating_income %>/month</li>
        <li class="list-group-item"><strong>Cash Flow:</strong> $<%= @deal.cash_flow %>/month</li>
        <li class="list-group-item"><strong>Cash on Cash Return:</strong> <%= @deal.cash_on_cash_return %>%</li>
        <li class="list-group-item"><strong>Max Purchase Price:</strong> $<%= @deal.max_purchase_price 1000, 100 %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseHackHunter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "rails-ujs" %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= current_user.email %><br>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <%= link_to "Account Settings", edit_user_registration_path %>
    <% else %>
      <%= link_to "Log In", new_user_session_path %><br>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>